import { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';

type Day = { date: string; level: number; detail: string };
interface Props { title: string; days: Day[]; mode?: 'nutrition' | 'workout'; }

export default function GitHubCalendar({ title, days, mode = 'workout' }: Props) {
  const [month, setMonth] = useState(new Date());
  const [selected, setSelected] = useState<Day | null>(null);
  const byDate = useMemo(() => new Map(days.map((day) => [day.date, day])), [days]);
  const cells = useMemo(() => { const start = new Date(month.getFullYear(), month.getMonth(), 1); const offset = (start.getDay() + 6) % 7; return Array.from({ length: 49 }, (_, index) => { const day = new Date(month.getFullYear(), month.getMonth(), index - offset + 1); return { date: day.toISOString().slice(0, 10), current: day.getMonth() === month.getMonth() }; }); }, [month]);
  const color = (day?: Day) => { if (!day) return '#d1d5db'; if (mode === 'workout') return '#22c55e'; return day.level >= 3 ? '#ef4444' : day.level >= 1 ? '#eab308' : '#22c55e'; };
  return <div className="rounded-2xl border border-border bg-[#1A1A2E] p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-text">{title}</h3><div className="flex gap-2"><button type="button" aria-label="Предыдущий месяц" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} className="btn-secondary p-2"><ChevronLeft size={15} /></button><button type="button" aria-label="Следующий месяц" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} className="btn-secondary p-2"><ChevronRight size={15} /></button></div></div><p className="mb-4 text-xs capitalize text-text-tertiary">{month.toLocaleDateString('ru-RU', { month: 'long', year: 'numeric' })}</p><div className="grid grid-cols-7 gap-1" style={{ gap: 4 }}>{cells.map((cell) => { const day = byDate.get(cell.date); return <button key={cell.date} type="button" disabled={!cell.current} onClick={() => setSelected(day ?? { date: cell.date, level: 0, detail: 'Нет данных' })} aria-label={`${cell.date}: ${day?.detail || 'Нет данных'}`} className={`h-3 w-3 rounded-sm transition-transform hover:scale-125 ${!cell.current ? 'opacity-0' : ''}`} style={{ backgroundColor: color(day) }} />; })}</div><div className="mt-4 flex items-center gap-2 text-[10px] text-text-tertiary"><span>Меньше</span>{['#d1d5db', '#22c55e', '#eab308', '#ef4444'].map((value) => <span key={value} className="h-3 w-3 rounded-sm" style={{ backgroundColor: value }} />)}<span>Больше</span></div>{selected && <div className="mt-4 rounded-lg border border-accent-blue/30 bg-accent-blue/10 p-3 text-xs text-text-secondary"><strong className="text-text">{selected.date}</strong>: {selected.detail}<button type="button" onClick={() => setSelected(null)} className="ml-2 text-accent-blue">Закрыть</button></div>}</div>;
}
